Add error checking in case ffmpeg download error occurs

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,8 +1,16 @@
 #!/bin/sh
 
+
 indent() {
   sed -u 's/^/       /'
 }
+
+
+function die() {
+  echo >&2 $*
+  exit 1
+}
+
 
 echo "-----> Install ffmpeg"
 BUILD_DIR=$1
@@ -16,7 +24,7 @@ mkdir -p $VENDOR_DIR
 cd $VENDOR_DIR
 mkdir -p ffmpeg
 cd ffmpeg
-curl -L --silent $DOWNLOAD_URL | tar xJ --strip-components=1
+curl -L --silent $DOWNLOAD_URL | tar xJ --strip-components=3 || die "error: unable to download ffmpeg"
 
 echo "exporting PATH" | indent
 PROFILE_PATH="$BUILD_DIR/.profile.d/ffmpeg.sh"
